# Site settings
title: toobaamiri | طوبی امیری
email: amirit074@gmail.com
description: دانشجوی کامپیوتر _نرم افزار
baseurl: "http://toobaamiri.ir/"
url: "http://toobaamiri.ir"
twitter: _Karamii
github:  toobaamiri
behance: HosseinKarami
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]